dogs/urls.py
from django.urls import path
from .views import (
    add_dog_to_profile,
    index,
    breeds,
    dogs_list,
    dog_create,
    dog_update,
    dog_delete,
    dog_read,
    all_dogs,
    remove_dog_from_profile
)

app_name = 'dogs'

urlpatterns = [
    path('', index, name='index'),
    path('breeds/', breeds, name='breeds'),
    path('dogs/', dogs_list, name='dogs_list'),
    path('dogs/all/', all_dogs, name='all_dogs'),
    path('dogs/create/', dog_create, name='dog_create'),
    path('dogs/<int:pk>/', dog_read, name='dog_read'), # Перед update и delete
    path('dogs/<int:pk>/update/', dog_update, name='dog_update'),
    path('dogs/<int:pk>/delete/', dog_delete, name='dog_delete'),
    path('dogs/<int:dog_id>/add_to_profile/', add_dog_to_profile, name='add_to_profile'),
    path('dogs/<int:dog_id>/remove_from_profile/', remove_dog_from_profile, name='remove_dog_from_profile'),
]

dogs/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings

User = get_user_model()  # Получаем модель пользователя

class Breed(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название породы', unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Порода'
        verbose_name_plural = 'Породы'

class Dog(models.Model):
    name = models.CharField(max_length=100, verbose_name='Кличка')
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, related_name='dogs', verbose_name='Порода')
    age = models.PositiveIntegerField(verbose_name='Возраст')
    description = models.TextField(blank=True, verbose_name='Описание')
    image = models.ImageField(upload_to='dog_images/', blank=True, null=True, verbose_name='Фотография')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='dogs', verbose_name='Владелец')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Собака'
        verbose_name_plural = 'Собаки'

dogs/forms.py
from django import forms
from .models import Dog

class DogForm(forms.ModelForm):
    class Meta:
        model = Dog
        fields = ['name', 'breed', 'image', 'age', 'description']

dogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Breed, Dog
from .forms import DogForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods

@require_http_methods(["POST"])
@login_required
def add_dog_to_profile(request, dog_id):
    dog = get_object_or_404(Dog, pk=dog_id)
    dog.owner = request.user
    dog.save()
    return redirect(request.META.get('HTTP_REFERER', reverse('dogs:dogs_list')))

@require_http_methods(["DELETE"])
@login_required
def remove_dog_from_profile(request, dog_id):
   dog = get_object_or_404(Dog, pk=dog_id, owner=request.user)
   dog.owner = None
   dog.save()
   return JsonResponse({'message': 'Собака успешно удалена из профиля.'})

@login_required
def index(request):
    title = 'Главная страница'
    context = {'title': title}
    return render(request, 'dogs/index.html', context)

@login_required
def breeds(request):
    title = 'Породы собак'
    breeds = Breed.objects.all()  # Получаем все породы
    breeds_with_dogs = {breed: Dog.objects.filter(breed=breed) for breed in breeds}  # Получаем собак по породам
    context = {'title': title, 'breeds_with_dogs': breeds_with_dogs}
    return render(request, 'dogs/breeds.html', context)


@login_required
def dogs_list(request):
    title = 'Список всех собак'
    dogs = Dog.objects.all()  # Получаем всех собак
    context = {'title': title, 'dogs': dogs}
    return render(request, 'dogs/dogs_list.html', context)

@login_required
def dog_create(request):
    title = 'Добавить собаку'
    form = DogForm()  # Инициализация формы
    if request.method == 'POST':
        form = DogForm(request.POST, request.FILES)
        if form.is_valid():
            dog = form.save()
            return redirect('dogs:dogs_list')
    context = {'title': title, 'form': form}
    return render(request, 'dogs/dog_create.html', context)

@login_required
def dog_update(request, pk):
    title = 'Редактировать информацию о собаке'
    dog = get_object_or_404(Dog, pk=pk)
    if request.method == 'POST':
        form = DogForm(request.POST, request.FILES, instance=dog)
        if form.is_valid():
            form.save()
            return redirect('dogs:dog_read', pk=dog.pk)
    else:
        form = DogForm(instance=dog)
    context = {'title': title, 'form': form, 'dog': dog}
    return render(request, 'dogs/dog_update.html', context)

@login_required
def dog_delete(request, pk):
    title = 'Удалить собаку'
    dog = get_object_or_404(Dog, pk=pk)
    dog.delete()  # Удаляем собаку
    return redirect(reverse('dogs:dogs_list'))  # Перенаправляем на список собак

@login_required
def dog_read(request, pk):
    title = 'Информация о собаке'
    dog = get_object_or_404(Dog, pk=pk)
    context = {'title': title, 'dog': dog}
    return render(request, 'dogs/dog_read.html', context)  # Исправлен путь к шаблону

@login_required
def all_dogs(request):
    title = 'Все собаки'
    dogs = Dog.objects.all()  # Получаем всех собак
    context = {'title': title, 'dogs': dogs}
    return render(request, 'dogs/all_dogs.html', context)

dogs/templates/dogs/breeds.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <h1 class="text-center mb-4">{{ title }}</h1>
    <div class="container">
        <div class="row">
            {% for breed, dogs in breeds_with_dogs.items %}
                <h2 class="col-12">{{ breed.name }}</h2>
                {% for dog in dogs %}
                    <div class="col-md-3 mb-4">  <!-- Изменено на col-md-3 -->
                        <div class="card">
                            {% if dog.image %}
                                <img src="{{ dog.image.url }}" alt="{{ dog.name }}" class="card-img-top" style="max-height: 150px; object-fit: cover;">
                            {% else %}
                                <img src="{% static 'images/default_dog.png' %}" alt="Default Dog" class="card-img-top" style="max-height: 150px; object-fit: cover;">
                            {% endif %}
                            <div class="card-body">
                                <p class="card-text mb-2"><small>Порода: {{ dog.breed.name }}</small></p>
                                <p class="card-text mb-2"><small>Возраст: {{ dog.age }} лет</small></p>
                                
                                <a href="{% url 'dogs:dog_read' dog.pk %}" class="btn btn-primary">Подробнее</a>
                                {% if user.is_authenticated %}
                                    
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

dogs/templates/dogs/dog_create.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить собаку</button>
    </form>
{% endblock %}

dogs/templates/dogs/dog_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Удалить собаку?</h1>
    <p>Вы уверены, что хотите удалить собаку "{{ dog.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'dogs:dog_read' pk=dog.pk %}" class="btn btn-secondary">Отмена</a>  {# Или другой URL для отмены #}
    </form>
{% endblock %}

dogs/templates/dogs/dog_read.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  <div class="container my-5">
    <h1 class="text-center mb-4">{{ title }}</h1>

    <div class="card mx-auto" style="width: 18rem;">
      {% if dog.image %}
        <img src="{{ dog.image.url }}" class="card-img-top" alt="{{ dog.name }}">
      {% else %}
        <img src="{% static 'images/default_dog.png' %}" class="card-img-top" alt="Изображение не доступно">
      {% endif %}
      <div class="card-body">
        <h5 class="card-title text-primary">{{ dog.name }}</h5>
        <p class="card-text"><strong>Порода:</strong> {{ dog.breed.name|default:"Не указана" }}</p>
        <p class="card-text"><strong>Возраст:</strong> {{ dog.age }} лет</p>

        {% if dog.description %}
          <p class="card-text"><strong>Описание:</strong> {{ dog.description }}</p>
        {% endif %}

        {% if user.is_authenticated and user == dog.owner %}
          <div class="d-flex justify-content-between align-items-center">
            <a href="{% url 'dogs:dog_update' pk=dog.pk %}" class="btn btn-primary">Редактировать</a>
            
          </div>
        {% endif %}

        <a href="{% url 'dogs:dogs_list' %}" class="btn btn-secondary mt-3">К списку собак</a>
      </div>
    </div>
  </div>
{% endblock %}

dogs/templates/dogs/dog_update.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить изменения</button>
    </form>

    

        К информации о собаке
    

{% endblock %}

dogs/templates/dogs/dogs_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1 class="text-center mb-4">Список всех собак</h1>
    <p class="text-center">Здесь вы можете найти информацию о собаках разных пород.</p>

    <div class="container">
        <div class="row">
            {% for dog in dogs %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        {% if dog.image %}
                            <img src="{{ dog.image.url }}" alt="{{ dog.name }}" class="card-img-top" style="max-height: 150px;">
                        {% else %}
                            <img src="" alt="Default Dog" class="card-img-top" style="max-height: 150px;">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title mb-2">{{ dog.name }}</h5>
                            <p class="card-text mb-2"><small>Порода: {{ dog.breed.name }}</small></p>
                            <p class="card-text mb-2"><small>Возраст: {{ dog.age }} лет</small></p>
                            <p class="card-text mb-2">{{ dog.description }}</p>
                            <a href="{% url 'dogs:dog_read' dog.pk %}" class="btn btn-primary">Подробнее</a>
                            {% if user.is_authenticated %}
                                <form method="post" action="{% url 'dogs:add_to_profile' dog_id=dog.pk %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-success">Добавить в профиль</button>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

dogs/templates/dogs/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <p>Добро пожаловать в питомник!</p>
{% endblock %}