dogs/urls.py
from django.urls import path
from .views import (
    add_dog_to_profile,
    index,
    breeds,
    dogs_list,
    dog_create,
    dog_update,
    dog_delete,
    dog_read,
    all_dogs,
    remove_dog_from_profile
)

app_name = 'dogs'

urlpatterns = [
    path('', index, name='index'),
    path('breeds/', breeds, name='breeds'),
    path('dogs/', dogs_list, name='dogs_list'),
    path('dogs/all/', all_dogs, name='all_dogs'),
    path('dogs/create/', dog_create, name='dog_create'),
    path('dogs/<int:pk>/', dog_read, name='dog_read'), # Перед update и delete
    path('dogs/<int:pk>/update/', dog_update, name='dog_update'),
    path('dogs/<int:pk>/delete/', dog_delete, name='dog_delete'),
    path('dogs/<int:dog_id>/add_to_profile/', add_dog_to_profile, name='add_to_profile'),
    path('dogs/<int:dog_id>/remove_from_profile/', remove_dog_from_profile, name='remove_dog_from_profile'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.user_profile, name='user_profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),  # Добавлено редактирование профиля
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
]

dogs/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings

User = get_user_model()  # Получаем модель пользователя

class Breed(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название породы', unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Порода'
        verbose_name_plural = 'Породы'

class Dog(models.Model):
    name = models.CharField(max_length=100, verbose_name='Кличка')
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, related_name='dogs', verbose_name='Порода')
    age = models.PositiveIntegerField(verbose_name='Возраст')
    description = models.TextField(blank=True, verbose_name='Описание')
    image = models.ImageField(upload_to='dog_images/', blank=True, null=True, verbose_name='Фотография')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='dogs', verbose_name='Владелец')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Собака'
        verbose_name_plural = 'Собаки'

dogs/forms.py
from django import forms
from .models import Dog

class DogForm(forms.ModelForm):
    class Meta:
        model = Dog
        fields = ['name', 'breed', 'image', 'age', 'description']

dogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Breed, Dog
from .forms import DogForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods

@require_http_methods(["POST"])
@login_required
def add_dog_to_profile(request, dog_id):
    dog = get_object_or_404(Dog, pk=dog_id)
    dog.owner = request.user
    dog.save()
    return redirect(request.META.get('HTTP_REFERER', reverse('dogs:dogs_list')))

@require_http_methods(["DELETE"])
@login_required
def remove_dog_from_profile(request, dog_id):
   dog = get_object_or_404(Dog, pk=dog_id, owner=request.user)
   dog.owner = None
   dog.save()
   return JsonResponse({'message': 'Собака успешно удалена из профиля.'})

@login_required
def index(request):
    title = 'Главная страница'
    context = {'title': title}
    return render(request, 'dogs/index.html', context)

@login_required
def breeds(request):
    title = 'Породы собак'
    breeds = Breed.objects.all()  # Получаем все породы
    breeds_with_dogs = {breed: Dog.objects.filter(breed=breed) for breed in breeds}  # Получаем собак по породам
    context = {'title': title, 'breeds_with_dogs': breeds_with_dogs}
    return render(request, 'dogs/breeds.html', context)


@login_required
def dogs_list(request):
    title = 'Список всех собак'
    dogs = Dog.objects.all()  # Получаем всех собак
    context = {'title': title, 'dogs': dogs}
    return render(request, 'dogs/dogs_list.html', context)

@login_required
def dog_create(request):
    title = 'Добавить собаку'
    form = DogForm()  # Инициализация формы
    if request.method == 'POST':
        form = DogForm(request.POST, request.FILES)
        if form.is_valid():
            dog = form.save()
            return redirect('dogs:dogs_list')
    context = {'title': title, 'form': form}
    return render(request, 'dogs/dog_create.html', context)

@login_required
def dog_update(request, pk):
    title = 'Редактировать информацию о собаке'
    dog = get_object_or_404(Dog, pk=pk)
    if request.method == 'POST':
        form = DogForm(request.POST, request.FILES, instance=dog)
        if form.is_valid():
            form.save()
            return redirect('dogs:dog_read', pk=dog.pk)
    else:
        form = DogForm(instance=dog)
    context = {'title': title, 'form': form, 'dog': dog}
    return render(request, 'dogs/dog_update.html', context)

@login_required
def dog_delete(request, pk):
    title = 'Удалить собаку'
    dog = get_object_or_404(Dog, pk=pk)
    dog.delete()  # Удаляем собаку
    return redirect(reverse('dogs:dogs_list'))  # Перенаправляем на список собак

@login_required
def dog_read(request, pk):
    title = 'Информация о собаке'
    dog = get_object_or_404(Dog, pk=pk)
    context = {'title': title, 'dog': dog}
    return render(request, 'dogs/dog_read.html', context)  # Исправлен путь к шаблону

@login_required
def all_dogs(request):
    title = 'Все собаки'
    dogs = Dog.objects.all()  # Получаем всех собак
    context = {'title': title, 'dogs': dogs}
    return render(request, 'dogs/all_dogs.html', context)

dogs/templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap CSS (CDN) -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- Custom styles -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  
</head>

<body>

<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'dogs:index' %}">Питомник</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dogs:index' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dogs:breeds' %}">Породы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dogs:dogs_list' %}">Собаки</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dogs:dog_create' %}">Добавить породу собаки</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                       
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:user_profile' %}">Профиль</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Выход</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:user_login' %}">Вход</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

<main role="main" class="container">
    {% block content %}
    {% endblock %}
</main>

<footer class="text-muted py-3">
    <div class="container">
        <p class="float-right">
            <a href="#">Наверх</a>
        </p>
        <p>Пример питомника</p>
    </div>
</footer>

 <!-- jQuery and Bootstrap (CDN) -->
 <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwQrGsZBaWqVCQRpFjpvV8KbskFY" crossorigin="anonymous"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

 <!-- Holder.js (CDN) - optional for placeholder images -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.9.9/holder.min.js" integrity="sha512-qN49TrH7yv2fM43f4F1W/0/V78D280Y9VjU096kUf0i20V9B1E1O9G/1eR7/9+bX0+s/1zY1yQ3eIu9T8Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

 <script>
    $(function () {
      var triggerTabList = [].slice.call(document.querySelectorAll('#myTab a'))
      triggerTabList.forEach(function (triggerEl) {
        var tabTrigger = new bootstrap.Tab(triggerEl)
  
        triggerEl.addEventListener('click', function (event) {
          event.preventDefault()
          tabTrigger.show()
        })
      })
    })
  </script>
</body>
</html>